---
title: "Project 1 Revised"
output: html_document
date: "2022-10-28"
---

##Importing data 
```{r, include = FALSE}
attacks <- read.csv("attacks.csv")
```
##Libraries
```{r, include = TRUE}
library(tidyr)
library(janitor)
library(ggplot2)
library(stringr)
```
##Cleaning data 
```{r, include = FALSE}

sharkattacks <- attacks[,-23:-24]
sharkattacks <- clean_names(sharkattacks)
remove_empty(sharkattacks, 
             which=c("rows","cols"))

#function for coercing data into functions
sharkfactor <- function(colname){
return(as.factor(colname)) 
}            

#make this a function for column that we want to use in the data frame
for(j in 1:length(sharkattacks$sex)){
  sharkattacks$sex[j] <-str_trim(sharkattacks$sex[j], side = "both")
}

#function to trim 
sharkstrim <- function(variable){
for(j in 1:length(variable)){
  variable[j] <-str_trim(variable[j], side = "both")
  }
}

#testing sharkstrim function 
sharkstrim(sharkattacks$sex)
sharkstrim(sharkattacks$country)
sharkstrim(sharkattacks$fatal_y_n)


#Subset and cleaning data for males vs females 
summary(factor(sharkattacks$sex))
sharkattacks_data <- subset(sharkattacks, sex == "M" | sex =="F")
summary(factor(sharkattacks_data$sex))
# sharkattacks_fatality <- subset(sharkattacks, fatal_y_n == "Y")
# summary(factor(sharkattacks_fatality$fatal_y_n))

```
##First plot 
```{r}
ggplot(sharkattacks_data, (aes(x = year))) +
  geom_bar(aes(fill = factor(sex, levels = c("M", "F")))) + 
  xlim(1900, 2018) + 
  xlab("Year") + 
  ylab("Number of Attacks")+
  theme_minimal()+
  theme(axis.text.x=element_text(size=15))+
  ggtitle("Recorded Shark Attacks 1900-2018")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))+
  theme(plot.title = element_text(size=22))+
  geom_hline(yintercept=50, 
             linetype="dashed", 
             color = "black",
             size=1)

```
```{r}
ggplot(sharkattacks_data[sharkattacks_data$fatal_y_n %in% "Y", ], aes(x = year)) +
  geom_bar(aes(fill = factor(sex, levels = c("M", "F")))) + 
  xlim(1900, 2018) + 
  xlab("Year") + 
  ylab("Number of Fatal Attacks")+   
  theme(axis.text.x=element_text(size=15))+
  ggtitle("Fatal Shark Attacks 1900-2018")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))+
  theme(plot.title = element_text(size=22))+
  geom_hline(yintercept=10, 
             linetype="dashed", 
             color = "black",
             size=1)

```


References:
https://r-graphics.org/recipe-legend-label-text
http://www.sthda.com/english/wiki/ggplot2-add-straight-lines-to-a-plot-horizontal-vertical-and-regression-lines
https://r-charts.com/distribution/violin-plot-group-ggplot2/
https://www.statology.org/add-text-to-ggplot/#:~:text=You%20can%20use%20the%20annotate,text%20to%20plots%20in%20ggplot2.&text=where%3A,the%20text%20should%20be%20placed.
http://www.sthda.com/english/wiki/ggplot2-colors-how-to-change-colors-automatically-and-manually

Make another visualization with #of fatalaties on y axis over time, comparing by sex 

