---
title: "Project 2"
output: html_document
date: "2022-10-28"
---

##Importing data 
```{r, include = FALSE}
attacks <- read.csv("../data/attacks.csv")
```
##Libraries
```{r, include = TRUE}
# Install packages below if you have never installed them before
# install.packages(tidyr)
# install.packages(janitor)
# install.packages(ggplot2)
# install.packages(stringr)
# install.packages(patchwork)

library(tidyr)
library(janitor)
library(ggplot2)
library(stringr)
library(patchwork)
```
##Cleaning data 
```{r, include = FALSE}
# Cleaning data
sharkattacks <- attacks[,-23:-24] # removing empty columns
sharkattacks <- clean_names(sharkattacks) # function used to clean names 
remove_empty(sharkattacks, 
             which=c("rows","cols")) # function used to remove empty columns and rows 

# Below from lines 35-39 is a loop within function to trim the extra spaces after character data from # the data set. Inputs are a data set with a column specified with a "$" and outputs are cleaned rows # within the columns that do not have unnecessary space.
sharkstrim <- function(variable){
for(j in 1:length(variable)){
  variable[j] <-str_trim(variable[j], side = "both")
  }
}

# using sharkstrim function (the function described above on the data set to remove spaces) for      
# specific columns sex and fatal_y_n
sharkstrim(sharkattacks$sex)
sharkstrim(sharkattacks$fatal_y_n)


#Subset and cleaning data for sex column 
summary(factor(sharkattacks$sex)) #used to check the factor levels before subsetting 
sharkattacks_data <- subset(sharkattacks, sex == "M" | sex == "F")
summary(factor(sharkattacks_data$sex))#used to check the factor levels after subsetting 


```
##First plot 
```{r}
# This is a function from lines 57-75 which outputs a plot of all of the shark attacks by sex of the victim. This   
# function has arguments so that the x axis limits and title of the graph can be changed. The inputs  # # are:
#        a -lower bound of axis (can be a number from 1800-1900)
#        b -upper bound of x axis (can be a number from 1800-1900)
#        title- title of visualization (must be in quotations)
# The outputs are a graph of all of the shark attacks between specified time and the frequency of the 
# that sex made up the attacks.
firstplot <- function(a, b, title) 
  {
ggplot(sharkattacks_data, (aes(x = year))) +
geom_bar(aes(fill = factor(sex, levels = c("M", "F")))) + 
xlim(a, b) + 
  xlab("Year") + 
  ylab("Number of Attacks")+
  theme_minimal()+
  scale_fill_manual("Sex", values = c("M"="blue", "F"="pink"))+
  theme(axis.text.x=element_text(size=10))+
  ggtitle(title)+
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size = 10,face="bold"))+
  theme(plot.title = element_text(size=12))+
  geom_hline(yintercept=50, 
             linetype="dashed", 
             color = "black",
             size=1)
}
# Patchwork package was used below in order to stitch two visualizations with different x-axis limits # together
a <- firstplot(1800, 2018, "Total Shark Attacks from 1800-2018")
b <- firstplot(2000, 2018, "Recent Shark Attacks from 2000-2018")
a+b

# Saving the png of the plots that were stitched together. This plot will be found in the results 
# folder
ggsave("sharkattacks_data1.png", bg="white", path = "../results")

```


```{r}
#Second plot code. Visualizes provoked attacks and frequency of sex of the victim from years 1900-2018
ggplot(sharkattacks_data[sharkattacks_data$fatal_y_n %in% "Y", ], aes(x = year)) +
  geom_bar(aes(fill = factor(sex, levels = c("M", "F")))) + 
  xlim(1900, 2018) + 
  xlab("Year") + 
  ylab("Number of Fatal Attacks")+   
  theme(axis.text.x=element_text(size=15))+
  ggtitle("Fatal Shark Attacks 1900-2018")+
  theme_minimal()+
  scale_fill_manual("Sex", values = c("M"="blue", "F"="pink"))+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))+
  theme(plot.title = element_text(size=22))+
  geom_hline(yintercept=10, 
             linetype="dashed", 
             color = "black",
             size=1)

#Saves the plot from the code above. This plot will be found in the results folder
ggsave("sharkattacks_data2.png", bg="white", path = "../results")

```



